version: '3.8'
services:
  #########################
  #### Postgres Container #
  #########################
  postgresqlDB:
    container_name: postgresqlDB
    image: postgres:10.0
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: book_marks
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - bookmarknet
  #########################
  #### Bookmarks #########
  #########################
  msvc-bookmark:
    container_name: msvc-bookmark
    image: msvc-bookmark:latest
    #image: drondon87/bookmark:latest
    ports:
      - '8001:8001'
    environment:
      PORT: 8001
      DB_HOST: postgresqlDB:5432
      DB_DATABASE: book_marks
      DB_USERNAME: postgres
      DB_PASSWORD: 1234
    networks:
      - bookmarknet
    depends_on:
      - postgresqlDB
    restart: always

volumes:
  data-postgres:
    name: data-postgres

networks:
  spring:
    name: bookmarknet